name: Maven CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  MAVEN_OPTS: "-Xmx1024m"
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: staging

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-artifact

      - name: Run tests
        run: mvn test

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: Deploy to staging
        run: echo "Deploying to staging..."
        env:
          STAGING_SECRET: ${{ secrets.STAGING_SECRET }}

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://prod.example.com
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}
